### ISSUE TITLE
Python wrapping of Node::set_external() method

### ISSUE THREAD

**Issue by acbauer** [LLNL/conduit#1149]
Is there an example on how to use Node::set_external() for strided Numpy arrays? I try to pass in a Schema and a Numpy array but I can't seem to properly set the Schema's DataType for the strided Numpy array information. I think this is because the Python wrapping of DataType just copies the DataType object so I'm modifying the new DataType object and not the one Schema's DataType member variable. See the following code as an example:
```
import conduit as cc
import numpy as np
z = np.zeros((10,3))
n = cc.Node()
s = cc.Schema()
d = s.dtype()
d.set_offset(0)
d.set_element_bytes(8)
d.set_number_of_elements(10)
d.set_stride(8)
n['values'].set_external(s, z)
print(n)
```

I also tried using `s.set(d)` which didn't seem to help. I probably have some of the values wrong for the DataType above but the code snippet is just intended to show what appears to be a bug.

**Comment by cyrush** [comment]
Here are a few examples of `set_external` with python:

https://github.com/LLNL/conduit/blob/50a5dbe8e975c1914187cf4ef3279b61f7753085/src/tests/conduit/python/t_python_conduit_node.py#L671

In these case we use RawArray to represent bytes as input to use with the schema. 

We also use numpy to create a view into those raw arrays, so that might be compatible with your use case. 

Also, `s.dtype()` will be a copy -- you will need to is  `s.set(d)`

I can explore the set external numpy case a bit more. 

You might even be able to `set_exernal` with a sliced view of the numpy array (avoid using schema?)

**Comment by acbauer** [comment]
I tried using `s.set(d)` but got confused by how information is printed out. It looks like that was working. I was also able to use `set_external` with a sliced numpy array so I think this issue can be closed. Thanks for the quick feedback!

**Comment by cyrush** [comment]
@acbauer awesome, glad you were able to get this working!
