### ISSUE TITLE
consider deprecating `fetch_child` and prefer better named method `fetch_existing`

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#525]

**Comment by cyrush** [comment]
@bryujin @xjrc what do you think about changing the name of `fetch_child` to `fetch_existing`

recall `fetch_child` is the explicit method that allows you to fetch existing parts of a conduit tree (it does not create nodes on the fly)

I feel `fetch_existing` is a much better name b/c `child` implies direct descendant.


I would keep both methods around for at least a release.

**Comment by xjrc** [comment]
The difference between `Node::fetch` and `Node::fetch_child` has always been a bit confusing to me (I have to carefully read the documentation every time I decide between the two), so I definitely like the idea of renaming `Node::fetch_child`. Just to make sure I'm understanding this correctly, here's what I envision the new behavior being:

- `Node& Node::fetch(const std::string& path)`: Fetch at `path` relative to the instance `Node`, creating new nodes as necessary to reach the path leaf (e.g. an empty object `Node` queried to fetch `"hello/world"` will create a direct descendant `hello` and a nested descendant `world`).
- `Node& Node::fetch_existing(const std::string& path)`: Fetch at `path` relative to the instance `Node`, but only if the path exists, and throw an error otherwise.

Is this correct? If so, then I'm all for the new naming scheme; it's complete and descriptive without being too verbose.

**Comment by cyrush** [comment]
@xjrc  -- yes that is correct, it seems like an improvement to me

**Comment by ryujin1** [comment]
@cyrush -- that sounds reasonable to me.

We probably originally named it "fetch_child" because it had similar properties of "child", which also can't create new nodes. The logic is a little bit of a stretch in retrospect, so getting rid of that naming is most likely a good thing.

**Comment by bryujin** [comment]
@cyrush -- that sounds reasonable to me.

We probably originally named it "fetch_child" because it had similar properties of "child", which also can't create new nodes. The logic is a little bit of a stretch in retrospect, so getting rid of that naming is most likely a good thing.

**Comment by cyrush** [comment]
resolved in #528
