### ISSUE TITLE
Type mismatch

### ISSUE THREAD

**Issue by corbett5** [LLNL/conduit#537]
On Quartz with clang9 I have in `conduit_bitwith_style_types.h`

```c++
typedef signed long         conduit_signed_long;
...
typedef conduit_signed_long conduit_int64;
...
#define CONDUIT_NATIVE_SIGNED_LONG_LONG  conduit_int64
```
Which results in `CONDUIT_NATIVE_SIGNED_LONG_LONG` being defined to `signed long`. Now even though both `long` and `long long` are 64 bits on this platform the compiler will still complain if I try to assign a pointer to one to the other.

**Comment by cyrush** [comment]
thanks @corbett5, it is common for long long and long to be the same # of bits - this is the case for most platforms except windows.  

The type selection logic should handle this but there could still be holes.


Can you share an example assignment error from your case?

**Comment by corbett5** [comment]
```c++
long long x = 5;
CONDUIT_NATIVE_LONG_LONG * xPtr = &x;
```

```
error: cannot initialize a variable of type 'conduit_int64 *' (aka 'long *') with an rvalue of type 'long long *'
    CONDUIT_NATIVE_LONG_LONG * xPtr = &x;
```

**Comment by cyrush** [comment]
`CONDUIT_NATIVE_SIGNED_LONG_LONG` tells you what type conduit uses to natively store signed long longs.  In this cases it is a signed long b/c those are bit-width equivalent.

Since there are less bit-width style types than there are native types, the mapping cannot be one to one with the c native types.

The `CONDUIT_NATIVE_*` types are part of the mapping logic that allows conduit nodes to naturally support compatible bit-width types, here is a long long example I tested on quartz with clang9:

```
TEST(conduit_test, ben)
{
   long long my_value = 10;
   conduit::Node n;
   n.set(my_value);

   n.print();

   long long v = n.value();
   long long *v_ptr = n.value();

   std::cout << "v " << v << std::endl;
   std::cout << "v_ptr " << v_ptr << std::endl;
   std::cout << "v_ptr[0] " << v_ptr[0] << std::endl;

}
```
 
```
[ RUN      ] conduit_test.ben
10
v 10
v_ptr 0x60ac80
v_ptr[0] 10
```

There is a lot of logic to make this work, it can't be done only through the type defs, but instead is tackled via the Node interface.  So, you should be able to set and access long long values + pointers through the node without any issues. Native c types or the conduit bit-width style types should work naturally. 

Except for very special cases, I don't think you should need to use `CONDUIT_NATIVE_*` types.

**Comment by cyrush** [comment]
@corbett5 hoping this info helped, can let me know if you have other questions related to this?

**Comment by corbett5** [comment]
This came up because I wrote a templated function similar to
```c++
template< typename T >
void foo( conduit::Node & node, T const * const pointer, int size )
{
  conduit::DataType dtype( conduitTypeInfo< T >::id, size);
  node.set_external( dtype, const_cast< typename conduitTypeInfo< T >::type * >( pointer ) );
}
```
and naturally `conduitTypeInfo< long long >::type` is mapped to `CONDUIT_NATIVE_SIGNED_LONG_LONG` which caused the `const_cast` to complain. I fixed it by changing to `const_cast< void * >` which is what the `conduit::node::set` expects anyway. Just thought I'd let you know.

**Comment by cyrush** [comment]
ok thanks,  the type specific set cases should already support that style of setting -- you can provide all the extra dtype info as well (length, offset, stride, ele bytes, endianness). 

https://github.com/LLNL/conduit/blob/8b4da06b7fa675fbdb73b505490142e5eae804ea/src/libs/conduit/conduit_node.hpp#L563

Perhaps your case fancier than I can imagine? I want to make sure there isn't a bad hole some where.  

Do you think it's ok to close this given the extra info?

**Comment by corbett5** [comment]
@cyrush I actually didn't see those overloaded methods. They my problem worse though since now the pointer passed to conduit needs to be strongly typed. So I'd have to do something like this
```c++
node.set_external( static_cast< typename conduitTypeInfo< T >::type * >( const_cast< void * >( ptr ) ),
                   size );
```

Go ahead and close it, the fix on my end is pretty easy with the `const_cast< void * >`.
