### ISSUE TITLE
Couple of question related to Conduit and Fortran API

### ISSUE THREAD

**Issue by uturuncoglu** [LLNL/conduit#730]
I have couple of questions related with Conduit that i could not find answer in the documentation.

- It seems that there is no Fortran documentation and i am referring `src/tests/conduit/fortran` directory. I just wonder that is there any documentation for Fortran.
- I just wonder that is there any example/way to pass data from Fortran to Python or maybe Fortran to C and then Python? I am experimenting to use Conduit to simplify the data exchange between Fortran and Python at this point. I have some initial implementation without using Conduit and that uses f90wrap to wrap the Fortran derived data types and expose it to Python but maybe i could do it in a more efficient, standardized and easy way if i use Conduit to define data structure in both side. Maybe this is not intention of the Conduit and if you clarify it that would be great.
- What is the real difference between Fortran node and node_object?

**Comment by cyrush** [comment]
@uturuncoglu  Thanks for your questions! Here is some info I hope helps:

1. Unfortunately, there is not a tutorial for fortran. I would love for it to exist -- Most of our fortran use cases involve wrapping mesh data in fortran and then presenting for processing in C++ (and from then some times on to Python)

2.  We do use Conduit as a path from Fortran ==> C++ ==> Python in Ascent (https://github.com/alpine-dav/ascent).  I will try to extract an example that shows this in a simpler context next week.   Depending on the nature of your data structures, it could be a good fit.  I think the key is if you want to leverage a dynamic hierarchical tree, while there are many paths to do so in Python - there aren't as many in Fortran.  And also, you can make sure you are zero copying bulk data (arrays) -- which provides efficiencies. 


3. In Fortran we provide two interfaces, 
  - node_object provides a Fortran object oriented interface, so you can call methods on the object using `%`
  - the other node interface is less object oriented, you pass the node as a cptr to other functions to perform operations 

Other than that detail they should provide the same functionality.

Here are some examples pulled from the unit tests (you may have seen these)

 Using the  fortran object oriented interface: 
```
   !--------------------------------------------------------------------------
    subroutine t_node_obj_set_int
        type(node) obj
        integer res

        obj = conduit_node_obj_create()
        call obj%set_int(42)
        call obj%print_detailed()
        res = obj%as_int()
        call conduit_node_obj_destroy(obj)
        
    end subroutine t_node_obj_set_int
```

 Using the "non" fortran object oriented interface: 
```
  !--------------------------------------------------------------------------
    subroutine t_node_set_int
        type(C_PTR) cnode
        integer res
        
        cnode = conduit_node_create()
        call conduit_node_set_int(cnode,42)
        res = conduit_node_as_int(cnode)
        call conduit_node_destroy(cnode)
       
    end subroutine t_node_set_int
```

**Comment by uturuncoglu** [comment]
@cyrush Thanks for your quick response and kindly help. You could see my comments below,

1 -  I just thought that it might be another source for Fortran examples but it seems there is no and it is totally fine for me. I could refer to the example and test codes for Fortran to learn more about it. They provide lots of information.

2 - If I could eliminate the data duplication along the way, Fortran ==> C++ ==> Python path is fine for me. It seems that zero copy approach provides that capability, which is great. I did not see any example about zero copy in Fortran side but maybe I missed it. I will look at more carefully. If you could prepare very simple tutorial that just send a node from Fortran to Python that would be great starting point for me. I don't want to take your time for it. If you don't have time for it that is fine and if you just point me some key information I could also work on it. I am not sure it is possible or not but is there a way to follow Python ==> C++ ==> Fortran path? In this case Python will send some data to Fortran interface. I am working on very simple application and if I could demonstrate interaction in two-way that would be great. 

3 - It is good to know that both approach do the similar things. I was thinking that Fortran OOP implementation might provide more rich features. I could stick to more simple node interface at this point.

**Comment by uturuncoglu** [comment]
@cyrush BTW, I could not find any example that demonstrates adding multiple dimensional array in Fortran side. There is an interface as `conduit_node_set_path_int32_ptr` but this gets number of elements. Is this also used for multi-dimensional pointers. If so, how this information will be converted to multi-dimensional representation in C++ or Python interface. Maybe there is a trick about it that I could not find it in the code. Thanks.

**Comment by cyrush** [comment]
there is a gap here, since the lowest level of conduit doens't support mult-d arrays -- only strided 1-d arrays. 

For these cases we, we store  `values` node with the data and `shape` with the shape info, and then reshape the view in python. 


LLNL's Axom project (which leverages conduit) provides a datastore called Sidre that has fortran support with views that provide shape info:

https://github.com/llnl/axom

That said the python story isn't complete yet.

Axom leverages shroud, which is a wrapping technology that does have support for Python, but I don't think Axom as a full python interface yet.

https://github.com/llnl/shroud

**Comment by uturuncoglu** [comment]
Okay, it is good to know the limitations. I think that storing `shape` is good idea at this point. Since the interface uses assumed shape arrays `(*)` I think there is no any limitation to pass multi-dimensional array to Conduit to pass pointer to the C/C++. The only confusing thing is the memory ordering differences in Fortran and C++ and when the data reach to the Python level this could require special attention. Do you have any suggestion or experience about it.

**Comment by cyrush** [comment]
This gets confusing -- however It turns out the in-memory layout of the bytes fast-varies the same way, the difference is in how the indexing constructs are used in the languages. 

I am working my way towards a fortran to python example, I'll try to demo this in the example.

**Comment by cyrush** [comment]
@uturuncoglu  I added a new standalone example project that demos C++ to Python, and Fortran to Python.

Here some details in the docs:

https://llnl-conduit.readthedocs.io/en/latest/tutorial_cpp_fort_and_py.html

And here is the source of the project:

https://github.com/LLNL/conduit/tree/develop/src/examples/cpp_fort_and_py

I don't have a multi-d array example in the fortran case, but I think this is a good initial demo of what is possible.

**Comment by uturuncoglu** [comment]
@cyrush Thank you very much for your great help. I'll look at it over the weekend and let you know. I could handle multi-d arrays by converting them to 1d and pass with that way and then reshape again in the destination. I was already doing it when I try to pass the data to ParaView Catalyst from Fortran before. It adds extra overhead but it could help to solve the problem.

**Comment by cyrush** [comment]
you are welcome + sounds good.

The example does demo how to reshape to multi-d in python, so I think parts of the puzzle are in place. 

Have a good weekend!

**Comment by uturuncoglu** [comment]
yes, you are right! Thanks again.

**Comment by uturuncoglu** [comment]
@cyrush I have just tested the approach that is shown in the examples but just for Fortran -> Python direction. I wrap the code that is found in the example around my demo application and try to send my custom node data. I could pass the node object to Python and see its content without any issue. That is really great! I still need to extend the node by adding more data and try to work with multi-d arrays but I have a foundation now that I could use it to build the demo application. I'll also test Python -> Fortran but first of all I would like to work on Fortran -> Python direction little bit more to make it more complete. 

At this point, I have following question;

- Is this example uses zero copy approach? I think that i am just exposing pointer to Python and it seems that there is no data copy over there but I am asking just to be sure.
- Is this approach could be also used in MPI based application? Let's assume that each processor creates its own node object and fill it with the chunk of data. What do I need to access the node object provided by each processor in Python side. Do I need to do any customization in any layer of the example?
- May I use the part of example code in my scientific application, which will be open source also? Is there any restriction about it in terms of license? As I know Conduit is an open source but I just want to be sure about it. 

BTW, thanks again for your great support and kindly help. If you are interested in and once i have the fully functional small demo app, I could share the details of the demo application with you and my plans to get your feedback and have information exchange. Anyway, let me know what do you think?

**Comment by uturuncoglu** [comment]
@cyrush it seems that MPI app also works. I could see different node instance for each MPI task under python. That is really great. Also, the Python code use the reference from C++ interface which indicates that there is no data copy. Anyway, thanks again.

**Comment by cyrush** [comment]
@uturuncoglu  Awesome, glad this worked for you!

Here are answers to your questions:

About zero-copy:

- For this case: We are wrapping Conduit Nodes, which is effectively zero-copying the Node object. There are data structures used to wrap across languages (bascially a void * in C, and a bit more in Python), but they should be trivial. 
  
  I want to mention there is another way to zero copy data. You can also zero-copy array leaves into a Conduit Node using `set_external`. With this approach you can take an existing array in Fortran (or numpy array in Python) and have Conduit simply describe the data (in contrast to copying it for ownership in the node, which is what `set` does). Lets say we `set_external` in Fortran, and then pass a Conduit node that includes this external array to Python. If I access the values as a numpy array and change them in Python, since they point to the same memory, the changes are there in Fortran as well.
 
  Here is a simpler example of `set_external`: 
https://ascent.readthedocs.io/en/latest/Tutorial_Intro_Conduit_Basics.html#zero-copy-vs-deep-copy-of-array-data

  The same the mechanism can be used across languages.

MPI: 

- I think you worked through an MPI example -- each MPI Task having an embedded interpreter should work.

Using the code:
- Yes, the code is open source with BSD 3 style license, so you are free to use it with that license. The embedded Python interpreter code I wrote for VisIt, then adapted for Ascent, and adapted now for this example. Both VisIt and Ascent also use BSD 3 style license, so the use is the same.

Again - glad this is working for you! 

And thanks for the dialog -- as a result we have a much need example demoing the C++, Fortran, and Python interaction.

**Comment by uturuncoglu** [comment]
@cyrush if I try to modify the code and run a python script rather than set of commands defined in `conduit_fort_to_py` it fails. Maybe I am doing something wrong. The script has following content,

```
print('Hello from Python, here is what you passed:')
print(my_node)
vals_view = my_node['values'].reshape(my_node['shape'])
print(vals_view)
```

and I add following `pyintp->run_script("process.py", py_mod_dict);` to the `conduit_fort_to_py` then I am getting segmentation fault. Do you have any idea? Thanks.

**Comment by cyrush** [comment]
@uturuncoglu  in this case `pyintp->run_script()` runs a string containing python source. I think `pyintp->run_script_file()` is what you are looking for. Give that a try. 

Also make sure to check the return code.  If something goes wrong you can get detailed error info using `pyintp->error_message()`

**Comment by uturuncoglu** [comment]
@cyrush i also use it and it was same. Anyway, let me handle error and see what happens.

**Comment by uturuncoglu** [comment]
@cyrush okay. using `run_script_file`is solved the problem. When running with MPI, Python layer does not know anything about the MPI and just run script 4 times with different input. I think it is already done under Ascent but how I could make Python side MPI aware? For example, if I want to combine the nodes coming from different processor, is it possible to do it in Python layer? or do I need to do it in Fortran/C++ layer. I think having capability to have parallelism under Python will be more flexible since I would like to use xarray/dask etc. Also, when I try to load MPI module in Python side with `from mpi4py import MPI` but the executable crashes.

**Comment by cyrush** [comment]
Yes, we do do this in ascent and use mpi4py.

Basically for script files, we only read the source file on one process and then broadcast to the rest for execution as a string. In our case, MPI is already initialized (by C++ or Fortran) and the key is making sure we pass the right communicator. 

(Edit)

We also do init with mpi4py in our python api tests:

https://github.com/Alpine-DAV/ascent/blob/develop/src/tests/ascent/python/t_python_ascent_mpi_render.py

To pass the communicator we use the fortran mpi handle b/c its an integer and easy to pass to via a conduit node:

Here is an example of us passing it in the cloverleaf proxy:

https://github.com/Alpine-DAV/ascent/blob/5e112348817471a7b2f2b21e7a449b5e46c06e88/src/examples/proxies/cloverleaf3d-ref/hydro.f90#L51

Here is an example of us using it on the other side in an embedded python interpret:

https://github.com/Alpine-DAV/ascent/blob/e3d810e2b00fab1026b60172ae6f27dfe757cd5f/src/examples/tutorial/cloverleaf_demos/python_extract/ascent_python_extract_histogram_demo.py#L53

There is some magic here (since we avoided mpi as a dependency for the python interpreter and the filter we create with it in ascent). This might be too in the weeds, here is where smoe of hte logic 

https://github.com/Alpine-DAV/ascent/blob/5e112348817471a7b2f2b21e7a449b5e46c06e88/src/ascent/runtimes/ascent_main_runtime.cpp#L699


From there you should be able to use mpi4py, and conduit also provides the relay mpi lib (which you can use in python)
with specific support for sending for Conduit Nodes.

https://llnl-conduit.readthedocs.io/en/latest/relay_mpi.html

**Comment by uturuncoglu** [comment]
@cyrush thanks for your detailed information. That is really helpful. I think that the problem that I faced in here is very basic. When I try to add `from mpi4py import MPI` to my Python script it crashes with segmentation fault. So, I have only single line in the script that tries to load the mpi4py. The trace is not usable even if i compile code with debug options and I could see any detail about error. If I use terminal to load the model, that is fine and it loads without any problem. So, I am trying to find the source of the problem. Maybe it is just a system issue.

**Comment by uturuncoglu** [comment]
@cyrush i have some progress about the issue. I think that it was related with the Python installation on my local MacOS. It might be something wrong with the Python or some of its modules installed with `brew`. To be sure I tried to run the same code on NCAR's Cheyenne  platform and it seems it is working and I could pass MPI communicator to Python. Thanks for your kindly and great help.

One of my observation is that if I did not include `Py_Finalize();` call at the end of the `conduit_fort_to_py` function, i could not see the returned stdout from Python script. So, I found that the finalize call flushes the stdout. Another workaround is to include `Py_UnbufferedStdioFlag = 1;` just before `Py_Initialize(); ` in `PythonInterpreter::initialize` function.

**Comment by cyrush** [comment]
@uturuncoglu  thanks for the update -- it does sound like some build or environment issue on your macOS system. Those can be hard to understand. I build my open development libs env's using spack, but that can be a steep learning curve.  And thanks for info on the buffering issue.

**Comment by uturuncoglu** [comment]
@cyrush is there any way to combine childs in node. I am using relay to combine data from different processor like `relay.mpi.gather_using_schema(n,rcv,0,comm_id)` but in this case `rcv` has children. I could access them as `rcv[0]["a"]` but I am not sure how those are combined and access as `rcv["a"]`. I could not find any examples in the documentation. Thanks.

**Comment by cyrush** [comment]
@uturuncoglu the `Node::update` method may help, that helps with a case like:

n1 -> a: [0,0]
n2 -> b: [1,1]

n1.update(n2)

n1 -> a:[0,0]
          b:[1,1]

Or are you trying to extend leaf that is array with the same type? 

We don't have a helper for extending, but we could add one.

**Comment by cyrush** [comment]
@uturuncoglu  I am going to close this issue since we now have better docs that help for this case. Please open another issue or ping me if you hit any new issues - and thanks again for the discussion here!

**Comment by uturuncoglu** [comment]
@cyrush thank you for your great support.
