### ISSUE TITLE
think through empty mesh considerations 

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#752]
(@xjrc changing this to an issue since we may take a different approach than in #751)

using conduit develop in ascent -  we hit an MPI hang where mesh index gen failed when trying to fetch coordsets from an empty mesh.

I think our case was due to changes in verify that now let emptys through. That I knew, but its been hard to detangle the cascade of differences. 

Ascent operations do often create "empty" domains. For example, a clip will not intersect all domains a mesh and many will be thrown out. Ascent has clean mesh logic that can cull out empty results, however that is now in rocky territory b/c it relied on verify being true to validate meshes and also `is_multi_domain`.

A few things:

- `mesh::bp::generate_index` always assumes that `coordsets` and `topologies` exist.  If a mesh can be empty, we need to figure out what to do in that case. 
 
- The most common pattern for creating mesh indexes is to create and hand the gen function a node to place results into. What does that mean when we could potentially create an empty index?
 
- If empty meshes are valid, the current `is_multi_domain` property implementation needs to be fixed, this logic wont work:
https://github.com/LLNL/conduit/blob/6f9d5b4a6ca8664e48f5b0e4bad1895b73a7da28/src/libs/blueprint/conduit_blueprint_mesh.cpp#L1427
 Since this is used to in several places, I also think this might be throwing off the logic for for number of domains. 

Given this experience - I am concerned by the burden of empty passing as a mesh. It seems like we may need to sprinkle more logic where previous calls to `verify` were sufficient. Not sure what our exposure is here.

**Comment by cyrush** [comment]
another note:

verify for the case where there is data always requires at least one `coordset` and one `topology`.   

That's consistent with our current docs https://llnl-conduit.readthedocs.io/en/latest/blueprint_mesh.html#protocol (which we mentioned might need to be changed if we keep this change)

**Comment by cyrush** [comment]
Trying to write a tests to explore what's a mesh. But I keep getting surprised.  I am 100% sure this is b/c I am rooted in the previous verify logic. 

That said, here is what my mind considers valid mesh bp:

`blueprint::mesh::verify`

single-domain -> conduit node that presents the proper tree structure 
multi-domain -> conduit node with children, and all  children present the proper single domain tree structure

`blueprint::mpi::mesh::verify`
mpi verify -> at least one MPI task presents a valid single- or multi-domain tree.

Can we have similar outline for the new logic to compare?

**Comment by xjrc** [comment]
Yes, that's a good idea. Just so we're crystal clear on all of the details, here's what the implementations were for all of the `mesh::verify` variants before and after 57702db0ce35b5cbeaee31179659a88385d94bce:

### Pre-57702db ###

- `blueprint::mesh::verify` uni-domain: 

### Post-57702db ###

**Comment by xjrc** [comment]
Yes, that's a good idea. Just so we're crystal clear on all of the details, here's what the implementations were for all of the `mesh::verify` variants before and after 57702db0ce35b5cbeaee31179659a88385d94bce:

### Pre-57702db ###

- `blueprint::mesh::verify` uni-domain: Given node contains at least a valid `coordset`, and optionally other valid paths
- `blueprint::mesh::verify` multi-domain: Given node is an object/list with children all conforming to uni-domain requirements (empty objects/lists accepted vacuously)
- `blueprint::mpi::mesh::verify`: At least one rank has a non-empty node that passes `blueprint::mesh::verify` (even if one or more ranks return false)

### Post-57702db ###

- `blueprint::mesh::verify` uni-domain: Given node contains at least a valid `coordset`, and optionally other valid paths (**no changes**)
- `blueprint::mesh::verify` multi-domain: Given node is of type empty/object/list with children all conforming to uni-domain requirements (**change: accept empty node types**)
- `blueprint::mpi::mesh::verify`: All ranks have a node that passes `blueprint::mesh::verify` (**change: all ranks instead of just one**)

The most impactful change appears to be the extension of `blueprint::mesh::verify` to accepting empty node types, which impacts all code that previously used `mesh::verify` to disqualify empty nodes from further processing. Since our production codes use `mesh::verify` as a sanity check on non-empty meshes (if at all), the potential set of impacted code is:

1. Ascent
2. Conduit-Carter
3. SAMRAI

Based on @nselliott's [comments](https://github.com/LLNL/conduit/pull/696#issuecomment-818306123) in #696, I think we can safely assume that SAMRAI is unaffected. I'm going to do some local testing on Conduit-Carter, but based on some quick glances at the source code, I think it's probably safe as well. Thus, unless I'm missing another dependent, the impacts are isolated to Ascent, so we should use the difficulty on adapting to the new paradigm in that code to determine how to proceed.

**Comment by xjrc** [comment]
Also, as a quick response to your note on multi-domain `blueprint::mesh::is_multi_domain`: I think that it does still work as intended (unless I'm missing something!). As an important caveat, this function works under the assumption that [`blueprint::mesh::verify`](https://github.com/LLNL/conduit/blob/6f9d5b4a6ca8664e48f5b0e4bad1895b73a7da28/src/libs/blueprint/conduit_blueprint_mesh.cpp#L1406) passes on the input.

In the case that an empty node is given, `Node::has_child` [will return false for any input](https://github.com/LLNL/conduit/blob/develop/src/libs/conduit/conduit_schema.cpp#L1242), which will cause the following `blueprint::mesh::is_multi_domain` logic to return true:

https://github.com/LLNL/conduit/blob/6f9d5b4a6ca8664e48f5b0e4bad1895b73a7da28/src/libs/blueprint/conduit_blueprint_mesh.cpp#L1427

I should probably add a test case just to double check as it doesn't look like there are any explicitly.

**Comment by cyrush** [comment]
Thanks @xjrc, based on my testing - the code doesn't match your Post-57702db expectations.


Here is what I see: 
 
Post-57702db:
============

`blueprint::mesh::verify` uni-domain:  **(now accepts empty nodes.)**

`blueprint::mesh::verify` multi-domain: Did not change. 

Also an empty node is flagged as a multi-domain mesh. 


```
bool
check_stuff(const Node &n)
{
    Node info;
    bool res = blueprint::mesh::verify(n,info);
    info.print();
    std::cout << "mesh verify result: " << res << std::endl;
    if(res)
    {
        std::cout << "number of domains: " << blueprint::mesh::number_of_domains(n) << std::endl;
        std::cout << "is multi domain: " << blueprint::mesh::is_multi_domain(n) << std::endl;
    }
    return res;
}

//-----------------------------------------------------------------------------
TEST(conduit_blueprint_mesh_verify, whats_a_mesh)
{
    Node n;
    bool res = check_stuff(n);
    // THIS IS A MESH
    EXPECT_TRUE(res);

    n.reset();
    n.append();
    n.append();
    res = check_stuff(n);
    // THIS IS NOT A MESH
    EXPECT_FALSE(res);
    
    
    res = check_stuff(n[0]);
    // THIS IS A MESH
    EXPECT_TRUE(res);

    n.reset();
    n.append().append();
    n.append().append();
    res = check_stuff(n);

    // THIS IS NOT A MESH
    EXPECT_FALSE(res);

    n.reset();
    Node &c = n.append();
    c["coordsets/coords/type"] = "uniform";
    c["coordsets/coords/dims/i"] = 2;
    c["coordsets/coords/dims/j"] = 2;
    // topo *is* required
    c["topologies/topo/type"] = "uniform";
    c["topologies/topo/coordset"] = "coords";

    res = check_stuff(n);
    // THIS IS A MESH AND A MULTI DOMAIN MESH (but with 1 domain, things align with expectations here)
    EXPECT_TRUE(res);

}
```

```
info: 
  - "mesh: is an empty mesh"
  - "mesh: is a multi domain mesh"
valid: "true"

mesh verify result: 1
number of domains: 0
is multi domain: 1

0: 
  coordsets: 
    valid: "false"
  errors: 
    - "mesh: missing child 'coordsets'"
    - "mesh: missing child 'topologies'"
  topologies: 
    valid: "false"
  valid: "false"
1: 
  coordsets: 
    valid: "false"
  errors: 
    - "mesh: missing child 'coordsets'"
    - "mesh: missing child 'topologies'"
  topologies: 
    valid: "false"
  valid: "false"
info: 
  - "mesh: is a multi domain mesh"
valid: "false"

mesh verify result: 0

info: 
  - "mesh: is an empty mesh"
  - "mesh: is a multi domain mesh"
valid: "true"

mesh verify result: 1
number of domains: 0
is multi domain: 1

0: 
  coordsets: 
    valid: "false"
  errors: 
    - "mesh: missing child 'coordsets'"
    - "mesh: missing child 'topologies'"
  topologies: 
    valid: "false"
  valid: "false"
1: 
  coordsets: 
    valid: "false"
  errors: 
    - "mesh: missing child 'coordsets'"
    - "mesh: missing child 'topologies'"
  topologies: 
    valid: "false"
  valid: "false"
info: 
  - "mesh: is a multi domain mesh"
valid: "false"

mesh verify result: 0

0: 
  coordsets: 
    valid: "true"
    coords: 
      type: 
        valid: "true"
      info: 
        - "mesh::coordset::uniform: 'type' has valid value 'uniform'"
      dims: 
        i: 
          valid: "true"
        j: 
          valid: "true"
        valid: "true"
      valid: "true"
  topologies: 
    valid: "true"
    topo: 
      coordset: 
        valid: "true"
      type: 
        valid: "true"
      info: 
        - "mesh::topology::uniform: 'type' has valid value 'uniform'"
      valid: "true"
  valid: "true"
info: 
  - "mesh: is a multi domain mesh"
valid: "true"

mesh verify result: 1
number of domains: 1
is multi domain: 1
```


VisIt is also part of the picture. VisIt has missing data support that may rely on mesh bp verify (not 100% sure). I think we also need to understand the index gen implications. If an empty mesh is valid uni-domain, we have to have extra guards for to create an index -- that would impact VisIt + Ascent.

**Comment by xjrc** [comment]
> Thanks @xjrc, based on my testing - the code doesn't match your Post-57702db expectations.
> 
> Here is what I see:
> 
> `blueprint::mesh::verify` uni-domain: **(now accepts empty nodes.)**
> 
> `blueprint::mesh::verify` multi-domain: Did not change.

I apologize for not being clear; there's ambiguity here because uni-domain and multi-domain `mesh::verify` use the same forward-facing interface, i.e. `blueprint::mesh::verify`. Here are the explicit functions I was referring to:

- `blueprint::mesh::verify` uni-domain: [`blueprint::mesh::verify_single_domain`](https://github.com/LLNL/conduit/blob/develop/src/libs/blueprint/conduit_blueprint_mesh.cpp#L540)
- `blueprint::mesh::verify` multi-domain: [`blueprint::mesh::verify_multi_domain`](https://github.com/LLNL/conduit/blob/develop/src/libs/blueprint/conduit_blueprint_mesh.cpp#L765)

If you look at [the diff for this change](https://github.com/LLNL/conduit/pull/731/files), only the `blueprint::mesh::verify_multi_domain` function was modified, which is why I listed `blueprint::mesh::verify_single_domain` as having no changes. However, your point regarding `blueprint::mesh::verify` accepting empty nodes [is certainly true](https://github.com/LLNL/conduit/pull/731#issuecomment-814366371).

> Also an empty node is flagged as a multi-domain mesh.

Yes, this is intentional. Since uni-domain meshes must be non-empty, an empty node most closely matches a multi-domain mesh with no entries, so that's how it's treated internally.

> VisIt is also part of the picture. VisIt has missing data support that may rely on mesh bp verify (not 100% sure). I think we also need to understand the index gen implications. If an empty mesh is valid uni-domain, we have to have extra guards for to create an index -- that would impact VisIt + Ascent.

Yes absolutely; this is another important node in the dependency graph that I hadn't considered. I will look over the VisIt plugin to gauge the difficulty of adapting to this change.

**Comment by xjrc** [comment]
Also, just so we have a log of the list of acceptable meshes, here's a text digest of the test case you posted above (I may have gotten test 3 wrong; please feel free to correct):

#### Test 1: Empty ####

```
### YAML ###

(empty)

### Results ###

mesh verify result: 1
number of domains: 0
is multi domain: 1
```

#### Test 2: Non-empty List ####

```
### YAML ###

[
  (empty),
  (empty)
]

### Results ###

mesh verify result: 0
```

#### Test 3: Embedded Lists ####

```
### YAML ###

[
  [
    (empty)
  ],
  [
    (empty)
  ]
]

### Results ###

mesh verify result: 0
```

#### Test 4: Real Mesh ####

```
### YAML ###

[
  coordsets:
    coords:
      type: uniform
      dims:
        i: 2
        j: 2
  topologies:
    topo:
      type: uniform
      coordset: coords
]

### Results ###

mesh verify result: 1
number of domains: 1
is multi domain: 1
```

**Comment by cyrush** [comment]
Yep, those look right.

**Comment by xjrc** [comment]
After looking over the VisIt source, I think empty node support will have minimal impact on the VisIt Blueprint plugin, due largely to how the code splits handling empty cases from validation cases. Here's a demonstrative example from [`avtBlueprintFileFormat.C`](https://github.com/visit-dav/visit/blob/develop/src/databases/Blueprint/avtBlueprintFileFormat.C):

https://github.com/visit-dav/visit/blob/develop/src/databases/Blueprint/avtBlueprintFileFormat.C#L1495

Even if an empty mesh is read in, it will be caught by the `data.dtype().is_empty()` check and properly handled. This pattern is replicated in all places where mesh data is read in and processed in this file. I do think this could be improved by lumping all of the empty cases together (e.g. `if(blueprint::mesh::number_of_domains(data) == 0) { ... }`), but this would be a fairly minor change.

I have some ideas for how Ascent could be fixed as well; I will submit them as a separate PR.

**Comment by cyrush** [comment]
I think this is resolved.
