### ISSUE TITLE
cmake exported targets quandry

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#753]
`find_dependency` is recommend to find deps in exported targets -- however it seems to adjust the cmake policy stack in some way?

With `find_package` you can adjust policies with push/pop.

Will stick with `find_package` until this quandary is resolved.

**Comment by mathstuf** [comment]
How does it interfere with the policy stack? `find_dependency` is a simple macro around `find_package` without any policy logic.

**Comment by cyrush** [comment]
Here is more context:

Looking at the logic that imports HDF5 targets for downstream users:

https://github.com/LLNL/conduit/blob/eb7dfce2229aac3b9644d422a44948509034e3c6/src/config/conduit_setup_deps.cmake#L41


I tried changing this to use `find_dependency`, instead of `find_package` (so the options like quiet, etc would be automatically passed on).  When I did this, I started seeing warnings related to `CMP0074`, so I stuck with  `find_package`.  I didn't explore deeper. Might be CMake version dependent, not sure. 

I take it it should work, but I didn't have time to explore the surprise.

**Comment by mathstuf** [comment]
Oh. I would just ignore that because it is saying that there is a `_ROOT` variable that might change lookup behavior that is being ignored in the current call. This is completely up to the consuming project based on its minimum CMake version.

FWIW, in VTK I just ignored `find_dependency` because I needed to pass other information down (version requirements, components, etc.) in the general case, but I guess if the dependency tree is much more static, `find_dependency` can work suitably.

**Comment by cyrush** [comment]
Thanks for the additional context.  I added the policy adjustment at the request of someone downstream to reduce noise when they built using conduit. 

I think for now we will just stick with `find_package` as well, since this gives more flexibility even if `find_dependency` could make things a little easier in theory.

**Comment by cyrush** [comment]
Closing, we will stick with find_package for now.
